import Sujal from 'assets/headshots/Sujal.jpg';

const committee = [
  {
    name: 'Emma Sementi',
    position: 'Director of EOH',
    major: 'Ag. and Bio Engineering',
    year: 'Senior',
    image: Sujal,
  },
  {
    name: 'Emily Roth',
    position: 'Director of Exhibits',
    major: 'Systems Engineering',
    year: 'Junior',
    image: Sujal,
  },
  {
    name: 'Brandon Wang',
    position: 'Senior Corporate Director',
    major: 'Computer Science',
    year: 'Junior',
    image: Sujal,
  },
  {
    name: 'Ryan Schiffer',
    position: 'Junior Corporate Director',
    major: 'Civil and Env. Engineering',
    year: 'Senior',
    image: Sujal,
  },
  {
    name: 'Sabrina Moheydeen',
    position: 'Junior Corporate Director',
    major: 'Computer Engineering',
    year: 'Sophomore',
    image: Sujal,
  },
  {
    name: 'Maneesh Madala',
    position: 'Director of Judging and Awards',
    major: 'Computer Engineering',
    year: 'Junior',
    image: Sujal,
  },
  {
    name: 'Bella Ramos',
    position: 'Director of Creative Design',
    major: 'Communications',
    year: 'Freshman',
    image: Sujal,
  },
  {
    name: 'Savni Nagarkar',
    position: 'Director of Facilites and Equipment',
    major: 'Computer Engineering',
    year: 'Junior',
    image: Sujal,
  },
  {
    name: 'Siddharth Kandimalla',
    position: 'Director of Traffic and Safety',
    major: 'Mechanical Engineering',
    year: 'Sophomore',
    image: Sujal,
  },
  {
    name: 'Alara Sunar',
    position: 'Director of Vistor’s Information',
    major: 'Bioengineering',
    year: 'Sophomore',
    image: Sujal,
  },
  {
    name: 'Samira Tungare',
    position: 'Director of External Marketing',
    major: 'Electrical Engineering',
    year: 'Senior',
    image: Sujal,
  },
  {
    name: 'Alice Perng',
    position: 'Director of Internal Marketing',
    major: 'Computer Science',
    year: 'Junior',
    image: Sujal,
  },
  {
    name: 'Priya Bharath',
    position: 'Director of Internal Relations',
    major: 'Material Science and Eng.',
    year: 'Senior',
    image: Sujal,
  },
  {
    name: 'Sujal Sutaria',
    position: 'Treasurer',
    major: 'Electrical Engineering',
    year: 'Senior',
    image: Sujal,
  },
  {
    name: 'Ammar Master',
    position: 'Director of HSDC',
    major: 'Computer Engineering',
    year: 'Junior',
    image: Sujal,
  },
  {
    name: 'Isha Tyle',
    position: 'Director of MSDC',
    major: 'Mechanical Engineering',
    year: 'Junior',
    image: Sujal,
  },
  {
    name: 'Michael Gale',
    position: 'MRDC Director',
    major: 'Idustrial Engineering',
    year: 'Senior',
    image: Sujal,
  },
  {
    name: 'Lauren Ho',
    position: 'Director of Technology',
    major: 'Computer Science',
    year: 'Sophomore',
    image: Sujal,
  },
  {
    name: 'Rahul Krishnan',
    position: 'Director of Technology',
    major: 'Computer Engineering',
    year: 'Senior',
    image: Sujal,
  },
  {
    name: 'Shreya Gargya',
    position: 'Director of Special Events',
    major: 'Bioengineering',
    year: 'Sophomore',
    image: Sujal,
  },
  {
    name: 'Jackie Way',
    position: 'Director of Advancement',
    major: 'Material Science & Eng.',
    year: 'Junior',
    image: Sujal,
  },
  {
    name: 'Daniela Zieba',
    position: 'Director of Startup Showcase',
    major: 'Computer Science',
    year: 'Sophomore',
    image: Sujal,
  },
  {
    name: 'Nafiz Rahman',
    position: 'Historian',
    major: 'Computer Science',
    year: 'Sophomore',
    image: Sujal,
  },
  {
    name: 'Michaela Patton',
    position: 'EFC Representative',
    major: 'Computer Science',
    year: 'Freshman',
    image: Sujal,
  },
  {
    name: 'Dev Satpathy',
    position: 'EFC Representative',
    major: 'Computer Science',
    year: 'Freshman',
    image: Sujal,
  },
];

export default committee;
